SYMFONY/src/Entity/Creations.php
<?php

namespace App\Entity;

use App\Repository\CreationsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreationsRepository::class)]
class Creations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imagePath = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column]
    private ?int $Taille = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $Prix = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(?string $imagePath): static
    {
        $this->imagePath = $imagePath;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getTaille(): ?int
    {
        return $this->Taille;
    }

    public function setTaille(int $Taille): static
    {
        $this->Taille = $Taille;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }
}

SYMFONY/src/Form/CreationsType.php
<?php

namespace App\Form;

use App\Entity\Creations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Image')
            ->add('Nom')
            ->add('Taille')
            ->add('Description')
            ->add('Prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Creations::class,
        ]);
    }
}

SYMFONY/src/Controller/CreationsController.php
<?php

namespace App\Controller;

use App\Entity\Creations;
use App\Form\CreationsType;
use App\Repository\CreationsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/creations')]
class CreationsController extends AbstractController
{
    #[Route('/', name: 'app_creations_index', methods: ['GET'])]
    public function index(CreationsRepository $creationsRepository): Response
    {
        $creations = $creationsRepository->findAll();

        return $this->render('creations/index.html.twig', [
            'creations' => $creations,
        ]);
    }

    #[Route('/new', name: 'app_creations_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $creation = new Creations();
        $form = $this->createForm(CreationsType::class, $creation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($creation);
            $entityManager->flush();

            return $this->redirectToRoute('app_creations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('creations/new.html.twig', [
            'creation' => $creation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_creations_show', methods: ['GET'])]
    public function show(Creations $creation): Response
    {
        return $this->render('creations/show.html.twig', [
            'creation' => $creation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_creations_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Creations $creation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CreationsType::class, $creation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_creations_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('creations/edit.html.twig', [
            'creation' => $creation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_creations_delete', methods: ['POST'])]
    public function delete(Request $request, Creations $creation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$creation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($creation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_creations_index', [], Response::HTTP_SEE_OTHER);
    }
}

SYMFONY/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block head %}
            <nav class="nav">
                <ul>
                    <li><a href="{{ path('app_home') }}">Accueil</a></li>
                    <li><a href="{{ path('app_creations') }}" class="active">Créations</a></li>
                    <li><a href="{{ path('app_about') }}">À propos</a></li>
                    <li><a href="{{ path('app_contact') }}">Contact</a></li>
                    <li><a href="{{ path('app_login') }}">Connexion</a></li>
                </ul>
            </nav>
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}

        <footer class="footer">
            Informations de contact + Adresse du magasin + Horaires d'ouvertures et de fermetures
        </footer>

    </body>
</html>

SYMFONY/templates/creations/_delete_form.html.twig
<form method="post" action="{{ path('app_creations_delete', {'id': creation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ creation.id) }}">
    <button class="btn">Delete</button>
</form>

SYMFONY/templates/creations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

SYMFONY/templates/creations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Creations{% endblock %}

{% block body %}
    <h1>Edit Creations</h1>

    {{ include('creations/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_creations_index') }}">back to list</a>

    {{ include('creations/_delete_form.html.twig') }}
{% endblock %}

SYMFONY/templates/creations/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        {% for creation in creations %}
            <div class="col-md-3">
                <div class="card">
                    {% if creation.imagePath %}
                    <img src="{{ asset('uploads/creations/' ~ creation.ImagePath) }}" alt="{{ creation.nom }}" class="card-img-top">
                    {% else %}
                        <p>No image available</p>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ creation.nom }}</h5>
                        <p class="card-text">Taille: {{ creation.taille }} <br> Prix: {{ creation.prix }}€</p>
                        <p class="card-text">Détails: {{ creation.description }}</p>
                        <form action="#" method="GET">
                            {# <input id="prodId" name="prodId" type="hidden" value="{{ creation.reference }}"> #}
                            {# <input type="submit" class="btn btn-primary" value="Voir"> #}
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

SYMFONY/templates/creations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Creations{% endblock %}

{% block body %}
    <h1>Create new Creations</h1>

    {{ include('creations/_form.html.twig') }}

    <a href="{{ path('app_creations_index') }}">back to list</a>
{% endblock %}

SYMFONY/templates/creations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creations{% endblock %}

{% block body %}
    <h1>Creations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ creation.id }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ creation.Image }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ creation.Nom }}</td>
            </tr>
            <tr>
                <th>Taille</th>
                <td>{{ creation.Taille }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ creation.Description }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ creation.Prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_creations_index') }}">back to list</a>

    <a href="{{ path('app_creations_edit', {'id': creation.id}) }}">edit</a>

    {{ include('creations/_delete_form.html.twig') }}
{% endblock %}